name: Mafs Visual Tests

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: contains(github.event.pull_request.labels.*.name, 'visual-changes')
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
